### ISSUE TITLE
GitHub stats are not darkmode compatible

### ISSUE THREAD

**Issue by tsaglam** [dfuchss/dfuchss#1]
The GitHub stats in the profile readme are not darkmode compatible!
literally unusable, please fix asap!

Occured on Win 10, Firefox 101.0.1 64 Bit at 7:39pm CET, 31° celsius (ofc), 39% humidity 1008 hPa.

See image below:
![grafik](https://user-images.githubusercontent.com/4396919/175360819-62dec436-282a-4b85-a52e-7dd5dba79a26.png)

**Comment by dfuchss** [comment]
@tsaglam do you have any suggestions for a better theme 😂

**Comment by dfuchss** [comment]
And do you mean at CEST :D

**Comment by tsaglam** [comment]
> @tsaglam do you have any suggestions for a better theme 😂

I just use solarized colors: `&theme=vue&bg_color=27282200&text_color=5c6670` 😄
